# Build settings
theme: jekyll-theme-midnight

# Navbar links
nav_links:
  - name: "Home"
    link: "/"
  - name: "Projects"
    link: "/projects"
  - name: "Contact"
    link: "/contact"
  - name: "Resources"
    link: "/resources"
